Event_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noticeBoard.urls'))
]

articles/urls.py
from django.urls import re_path as url
# from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name='articles'

urlpatterns = [ 
     url(r'^$', views.article_list, name='list'),
     url(r'^create/$', views.article_create, name='create'),
     url(r'^(?P<slug>[\w-]+)/$', views.article_details, name='detail'),

]

events/urls.py
from django.contrib import admin
from django.urls import path
from events import views

urlpatterns = [
    path('events',views.event,name='events'),
    path('event/<str:id>',views.eventpost,name='eventpost'),
    path('create_event/', views.create_event, name='create_event'),
    path('add', views.ADD, name='add'),
    path('edit', views.Edit, name='edit'),
    path('update/<str:id>', views.Update, name='update'),
    path('delete/<str:id>', views.Delete, name='delete'),
    path('search', views.search, name='search'),
]   

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=20)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
     #add in thumbnail
    thumb=models.ImageField(default='default.png',blank=True)
     #add in author later 
    author=models.ForeignKey(User,default=None ,  on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+'...'
       

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from .import forms
# Create your views here.
def article_list(request):
    articles=Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_details(request,slug):
    # return HttpResponse(slug)
    article=Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',{'article':article})

def signup_view(request):
    return render(request, 'accounts/signup.html')

@login_required(login_url="/accounts/login/") # this decorator actually use to protect this view , means you can use this view unless or until you are not logged in . if user is not logged in it will redirect that url to  /accounts/login so that it non logged user redirect to login page 
def article_create(request):
    if request.method=='POST':
       form=forms.CreateArticle(request.POST,request.FILES)
       if form.is_valid():
          #save article to db
          instance=form.save(commit=False)
          instance.author=request.user
          instance.save()
          return redirect('articles:list')
    else:
     form=forms.CreateArticle()
    return render(request, 'articles/article_create.html',{'form': form})

articles/templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About page</title>
  </head>
  <body>
    This is about page
  </body>
</html>

articles/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Robotics event website  Article Page</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>
  <style>
body {
    background: url('https://img.freepik.com/premium-photo/robot-writing-desk_845712-397.jpg?w=1060') no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
  </style>
  <body>
    <header class="wrapper">
      <h1>
        <a href="{% url 'home' %}"
          ><img src="" alt="Robotics Event Article Page"
        /></a>
      </h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form
              class="logout-link"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'articles:create' %}" class="highlight" </a>New Article</li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif%}
        </ul>
      </nav>
    </header>
    <div class="wrapper">{% block content %} {% endblock %}</div>
  </body>
</html> 
<!-- "{% static 'logo.png' %} " -->

articles/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home page</title>
  </head>
  <body>
    This is Home page
  </body>
</html>